# Generated by Django 5.2.7 on 2025-10-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default='example', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
